### PR TITLE
fix: bump dotnet to 8.0 to support jellyfin 10.9

### LINKED ISSUE #7: Failing to work after 10.9.0
It fails automatically and I get this in the logs:

```[2024-05-12 13:38:35.717 -07:00] [ERR] [41] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.InternalItemsQuery.set_OrderBy(System.Collections.Generic.IReadOnlyList`1<System.ValueTuple`2<System.String,Jellyfin.Data.Enums.SortOrder>>)'.
   at Jellyfin.Plugin.RefreshSparse.RefreshScheduledTask.GetItems()
   at Jellyfin.Plugin.RefreshSparse.BaseRefreshTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)```

### PR DESCRIPTION
**Pull request by bin101**
fixes #7

### CODE REVIEW

**Comment by clowncracker** [comment]
@bin101 is there anything I can do now to test the change before this gets merged?  It doesn't seem the maintainer of the repo is very active and I'd love to get this plugin working again.

**Comment by bin101** [comment]
@clowncracker you could clone my branch, build the project on your own and copy the dll into the plugin folder. Don't forget to restart jellyfin after that.

**Comment by clowncracker** [comment]
How would I build the project?

**Comment by bin101** [comment]
@SenorSmartyPants would be great to get a review, without this the plugin is completely broken starting with jellyfin 10.9

**Comment by SenorSmartyPants** [comment]
Thanks for doing most of the work on this.

I've pushed a build and updated the manafest so JF should see and pull the new version.

I'm not updating to 10.9 until the patch releases slow down.

**Pull request merged**
